### ISSUE TITLE
Is it possible to use ES5 or transpile the code?

### ISSUE THREAD

**Issue by leandrooriente** [sindresorhus/is-observable#8]
As the code use arrow functions and there is no transpilation process, the code breaks on IE 11.

Is it possible to use a normal function instead of an arrow function?

```js
module.exports = value => Boolean(value && value[symbolObservable] && value === value[symbolObservable]());
```

To:
```js
module.exports = function(value) {
  return Boolean(value && value[symbolObservable] && value === value[symbolObservable]());
}
```

**Comment by kevva** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: sindresorhus/ama#446

If you use Webpack, check out babel-engine-plugin, which transpiles only the dependencies that needs to be transpiled.
